### ISSUE TITLE
HPPercent not updating

### ISSUE THREAD

**Issue by RagonEbker** [Roxeez/NtCore#5]
Hello 

I am getting all Monsters of a map with sender.Map.Monsters. But when i check the HP, it always stays the same, even when I attack or kill the monster. Is there a way to check the live status? 

And would it be possible to target or select a monster? I think its a little suspicious if i kill a monster before selecting ( sending ncif to the server).

Greetings

**Comment by Roxeez** [comment]
Yeah "su" packet handler is not yet implemented, so atm hp/mp are just uptaded on "in" packet and about targeting it can be done easily, i'm gonna add it.

**Comment by Roxeez** [comment]
Fixed #6
